version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - run:
          name: ngrok install
          command: sudo apt update && sudo apt install ngrok
      - run:
          name: ngrok login
          command: ngrok config add-authtoken 2lsr1PXYfHZ8wgLtdZYDzA7E6OB_42LS3yzkywFP5cVKxy5Zk
      - run:
          name: ngrok start
          command: ngrok http 3000
      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Start application
          command: npm run start
          background: true
      